spring:
  profiles:
    active: local
    group:
      local:
        - local
        - member-local
        - db-local
#        - aws-local
      dev:
        - dev
        - member-dev
        - db-dev
#        - aws-dev
      prod:
        - prod
        - member-prod
        - db-prod
#        - aws-prod
    include:
      - member
      - db
#      - aws
  #  devtools:
  #    livereload:
  #      enabled: true

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8091

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8091

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8091
